export default interface IParagonProperty {
    AboveGradeFinishedArea?: number
    AccessibilityFeatures: string[]
    Appliances: string[]
    ArchitecturalStyle: string[]
    AssociationFee?: number
    AssociationYN?: boolean
    AttachedGarageYN?: boolean
    Basement: string[]
    BasementYN?: boolean
    BathroomsFull?: number
    BathroomsHalf?: number
    BedroomsTotal?: number
    BelowGradeFinishedArea?: number
    BuilderName: any
    BuyerAgencyCompensation: string
    BuyerAgentFirstName?: string
    BuyerAgentFullName?: string
    BuyerAgentKey?: string
    BuyerAgentLastName?: string
    BuyerAgentMlsId: any
    BuyerFinancing: string[]
    BuyerOfficeKey?: string
    BuyerOfficeMlsId?: string
    BuyerOfficeName?: string
    CarportYN: any
    City: string
    CloseDate?: string
    ClosePrice?: number
    CoBuyerAgentFirstName: any
    CoBuyerAgentFullName: any
    CoBuyerAgentKey: any
    CoBuyerAgentLastName: any
    CoBuyerOfficeKey: any
    CoBuyerOfficeMlsId: any
    CoBuyerOfficeName: any
    CoListAgentFirstName: any
    CoListAgentFullName: any
    CoListAgentKey: any
    CoListAgentLastName: any
    CoListAgentMlsId: any
    CoListOfficeKey: any
    CoListOfficeMlsId: any
    CoListOfficeName: any
    CommunityFeatures: string[]
    ConcessionsComments?: string
    ConstructionMaterials: string[]
    Cooling: string[]
    CoolingYN?: boolean
    CountyOrParish: string
    CumulativeDaysOnMarket: any
    DaysOnMarket: number
    Directions: string
    DocumentsChangeTimestamp?: string
    DocumentsCount?: number
    DualVariableCompensationYN: any
    ElementarySchool?: string
    Exclusions?: string
    ExpirationDate: string
    ExteriorFeatures: any[]
    Fencing: any[]
    FireplaceFeatures: string[]
    FireplaceYN?: boolean
    FireplacesTotal?: number
    FoundationDetails: string[]
    FrontageLength?: string
    FrontageType: string[]
    GarageSpaces?: number
    GarageYN?: boolean
    GreenBuildingVerificationType: any[]
    GreenEnergyEfficient: any[]
    GreenSustainability: any[]
    GreenWaterConservation: any[]
    Heating: string[]
    HeatingYN?: boolean
    HighSchool?: string
    HighSchoolDistrict?: string
    HomeWarrantyYN: any
    HorseYN?: boolean
    Inclusions?: string
    InteriorFeatures: string[]
    InternetAddressDisplayYN?: boolean
    InternetEntireListingDisplayYN: boolean
    Latitude: any
    LaundryFeatures: string[]
    Levels: string[]
    ListAgentEmail?: string
    ListAgentFirstName: string
    ListAgentFullName: string
    ListAgentKey: string
    ListAgentLastName: string
    ListAgentMiddleName?: string
    ListAgentMlsId: string
    ListOfficeKey: string
    ListOfficeMlsId: string
    ListOfficeName: string
    ListPrice: number
    ListTeamName: any
    ListingContractDate: string
    ListingId: string
    ListingKey: string
    ListingService?: string
    ListingTerms: string[]
    LivingArea?: number
    LivingAreaSource: any
    Longitude: any
    LotFeatures: string[]
    LotSizeAcres?: number
    LotSizeDimensions?: string
    LotSizeSource?: string
    LotSizeSquareFeet?: number
    MLSAreaMinor: string
    MiddleOrJuniorSchool?: string
    MlsStatus: string
    ModificationTimestamp: string
    NewConstructionYN: any
    OccupantType: any
    OffMarketDate: string
    OriginalEntryTimestamp?: string
    OriginalListPrice: number
    OriginatingSystemID: string
    OriginatingSystemName: string
    OtherEquipment: any[]
    OtherStructures: string[]
    OwnerName: any
    ParcelNumber: string
    ParkingFeatures: string[]
    PatioAndPorchFeatures: string[]
    PhotosChangeTimestamp: string
    PhotosCount: number
    PoolFeatures: string[]
    PoolPrivateYN?: boolean
    PostalCity?: string
    PostalCode: string
    PriceChangeTimestamp?: string
    PrivateOfficeRemarks: any
    PrivateRemarks?: string
    PropertyCondition: any[]
    PropertySubType: any
    PropertyType: string
    PublicRemarks: string
    PurchaseContractDate?: string
    SecurityFeatures: string[]
    Sewer: string[]
    ShowingInstructions: any
    SpaYN?: boolean
    SpecialListingConditions: string[]
    StandardStatus: string
    StateOrProvince: string
    StatusChangeTimestamp: string
    StreetDirPrefix?: string
    StreetName: string
    StreetNumber?: string
    StreetNumberNumeric: any
    StreetSuffix?: string
    SubAgencyCompensation: string
    SubdivisionName?: string
    TaxAnnualAmount: number
    TaxAssessedValue?: number
    TaxYear: number
    Township: string
    UnitNumber: any
    Utilities: string[]
    View: string[]
    VirtualTourURLBranded: any
    VirtualTourURLUnbranded?: string
    WaterBodyName?: string
    WaterSource: string[]
    WaterfrontFeatures: string[]
    WaterfrontYN?: boolean
    WindowFeatures: string[]
    YearBuilt?: number
    YearBuiltSource?: string
    Zoning?: string
    Full_Baths_Upper?: string
    _1_Or_2_Baths_Upper?: string
    Full_Baths_Main?: string
    _1_Or_2_Baths_Main?: string
    _1_Or_2_Baths_Lower?: string
    Full_Baths_Lower?: string
    Bedroom_5_Dim?: string
    Other_Room_2_Dim?: string
    Other_Room_1_Dim?: string
    Primary_Bed_Dim_258?: string
    Family_Room_Dim_257?: string
    Dining_Room_Dim_256?: string
    Living_Or_Great_Dim_254?: string
    Other_Room_3_Lvl?: string
    Other_Room_4_Lvl?: string
    Other_Room_2_Lvl?: string
    Other_Room_1_Lvl?: string
    Kitchen_Dim_255?: string
    Bedroom_2_Dim_259?: string
    Bedroom_3_Dim_260?: string
    Bedroom_4_Dim_261?: string
    Dining_Area_Lvl?: string
    Other_Room_3_Dim?: string
    Dining_Area_Dim?: string
    Other_Room_4_Dim?: string
    Primary_BedRm_Lvl_67?: string
    Bedroom_2_Lvl_68?: string
    Bedroom_4_Lvl_70?: string
    Bedroom_3_Lvl_69?: string
    Family_Room_Lvl?: string
    Dining_Room_Lvl_65?: string
    Kitchen_Lvl_64?: string
    Living_Or_Great_Room_Lvl_63?: string
    Laundry_Dim_82?: string
    Bedroom_5_Lvl?: string
    Other_Room_3?: string
    Other_Room_4?: string
    Farm_Y_Or_N?: string
    COMBO_Lock_Box_Code: any
    Other_Room_2?: string
    Subject_to_Policy_Letter: any
    Licensee_Interest: any
    Exclusive_Agency: any
    City_Town_orVillage: string
    Named_Exceptions: any
    Other_Room_1?: string
    WIREX_Photo_Share_ID?: string
    WIREX_Photo_Share?: string
    LockBox_Type: any
    Sale_Factors: any
    Competing_Written_Offers: any
    Other_Marketing_Area: any
    Auction: any
    County_Qtr_Section?: string
    Electronic_Consent: any
    TotBth?: string
    Multiple_Representation: any
    Open_House_Time: any
    Open_House_Time_2: any
    Broker_Open_Time: any
    Broker_Open_Comments: any
    First_Photo_Add_Dt?: string
    VTourURL: any
    Total_Assess_Year: any
    Type: any
    Showing_Start_Date?: string
    BuyerAgentEmail: any
    BuyerAgentPreferredPhone?: string
    BuyerAgentPreferredPhoneExt: any
    BuyerOfficeAOR?: string
    BuyerOfficeEmail?: string
    BuyerOfficePhone?: string
    BuyerOfficePhoneExt: any
    BuyerOfficeURL?: string
    CoBuyerAgentEmail: any
    CoBuyerAgentMlsId: any
    CoBuyerAgentPreferredPhone: any
    CoBuyerAgentPreferredPhoneExt: any
    CoBuyerOfficeAOR: any
    CoBuyerOfficeEmail: any
    CoBuyerOfficePhone: any
    CoBuyerOfficePhoneExt: any
    CoBuyerOfficeURL: any
    CoListAgentEmail: any
    CoListAgentMiddleName: any
    CoListAgentPreferredPhone: any
    CoListAgentPreferredPhoneExt: any
    CoListOfficeAOR: any
    CoListOfficeEmail: any
    CoListOfficePhone: any
    CoListOfficePhoneExt: any
    CoListOfficeURL: any
    DocumentsAvailable: string[]
    GrossIncome: any
    ListAgentPreferredPhone?: string
    ListAgentPreferredPhoneExt: any
    ListAgentURL?: string
    ListOfficeAOR?: string
    ListOfficeEmail?: string
    ListOfficePhone?: string
    ListOfficePhoneExt: any
    ListOfficeURL?: string
    ListingAgreement: any
    LockBoxType: any[]
    NetOperatingIncome?: number
    NumberOfUnitsTotal?: number
    OpenParkingSpaces: any
    OperatingExpense?: number
    ParkingTotal?: number
    SeniorCommunityYN: any
    SyndicationRemarks: any
    U1_Landlord_Pays_Heat: any
    U1_Landlord_Pays_Electric: any
    U1_Landlord_Pays_Wtr_Or_Sew: any
    U2_Landlord_Pays_Heat: any
    U2_Landlord_Pays_Electric: any
    U2_Landlord_Pays_Wtr_Or_Sew: any
    U1_Parking: any
    U2_Parking: any
    U3_Parking: any
    U4_Parking: any
    U3_Lease_Expiration_Date: any
    U2_Lease_Expiration_Date: any
    U1_Lease_Expiration_Date: any
    Unit_2: any
    Unit_3: any
    Unit_4: any
    U4_Lease_Expiration_Date: any
    Unit_1: any
    U1_Number__Bedrooms: any
    U1_Half_Baths: any
    U2_Number__Bedrooms: any
    U2_Full_Baths: any
    U2_Half_Baths: any
    U3_Number__Bedrooms: any
    U1_Full_Baths: any
    U2_SqFt: any
    U1_SqFt: any
    U3_Full_Baths: any
    U3_Half_Baths: any
    U3_SqFt: any
    U4_Number__Bedrooms: any
    U4_Full_Baths: any
    U3_Landlord_Pays_Heat: any
    U2_Mo_Rent: any
    U3_Mo_Rent: any
    U4_Mo_Rent: any
    U4_Half_Baths: any
    U1_Mo_Rent: any
    U4_SqFt: any
    U4_Landlord_Pays_Wtr_Or_Sew: any
    U4_Landlord_Pays_Electric: any
    U4_Landlord_Pays_Heat: any
    U3_Landlord_Pays_Electric: any
    U3_Landlord_Pays_Wtr_Or_Sew: any
    Improvements: any
    Number_of_1_Bedrooms: any
    Number_of_2_Bedrooms: any
    Number_of_3_Plus__Bedrooms: any
    Number_of_Efficiencies: any
    AdditionalParcelsDescription: any
    AdditionalParcelsYN: any
    BuyerAgentMiddleName: any
    BuyerAgentURL?: string
    CoBuyerAgentMiddleName: any
    CoBuyerAgentURL: any
    CoListAgentURL: any
    CommonInterest: any
    CurrentUse: string[]
    NumberOfLots?: number
    Possession: any[]
    RoadFrontageType: any[]
    RoadResponsibility: string[]
    RoadSurfaceType: string[]
    StructureType: any[]
    TaxLegalDescription?: string
    Topography?: string
    ZoningDescription?: string
    Specific_Builder_Required?: string
    AvailabilityDate: any
    LeaseConsideredYN?: boolean
    NumberOfUnitsInCommunity: any
    OwnerPays: any[]
    PetsAllowed: any[]
    RentIncludes: any[]
    ShowingContactName: any
    ShowingContactPhone: any
    Handicap_Access: any
    Price_Date: any
    Security_Deposit: any
    Showing_Contact_Email: any
    Lease_Term: any
    BuildingAreaSource: any
    BuildingAreaTotal?: number
    BuildingName?: string
    BusinessType: string[]
    GrossScheduledIncome?: number
    LeasableArea?: number
    LotSizeArea: any
    ParkName: any
    Roof: string[]
    StoriesTotal?: number
    TenantPays: any[]
    Approx_____Bldg_____DimenDot?: string
    Business_Sale?: string
    Ceiling_Height_Max?: string
    Ceiling_Height_Min?: string
    Number_of_Loading_Docks: any
    RE_Sale?: string
    Income_Or_Expenses_Year?: string
    AssociationAmenities: any[]
    AssociationFeeIncludes: any[]
    AssociationName: any
    Bedroom_2_Lvl_69: any
    Bedroom_2_Dim_260: any
    Bedroom_3_Lvl_70: any
    Bedroom_3_Dim_261: any
    Bedroom_4_Lvl_212: any
    Bedroom_4_Dim_262: any
    Dining_Room_Lvl_66: any
    Dining_Room_Dim_257: any
    Kitchen_Dim_256: any
    Kitchen_Lvl_65: any
    Living_Or_Great_Dim_255: any
    Living_Or_Great_Room_Lvl_64: any
    Primary_Bed_Dim_259: any
    Primary_BedRm_Lvl_68: any
    Pets_Allowed: any[]
    Family_Room_Dim_258: any
}